name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [ master ]

jobs:

# Build the Flask-GCBM REST API Setup

  build-gcbm-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rest_api_gcbm
    steps:
      - uses: actions/checkout@v2
      - name: Build FLINT UI Client container
        run: docker build -t gcbm-api .

  linting-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint source with Flake8
        run: |
          pip3 install flake8
          flake8 .
